-- Create a dedicated schema for Family Budget so several apps can share one
-- Oracle Autonomous Database without colliding. Run this as ADMIN (e.g. in the
-- OCI console → Database Actions → SQL). It contains no secrets.
--
-- Design: a SCHEMA-ONLY account (NO AUTHENTICATION) — it owns the tables but
-- cannot log in, so there is no extra password to manage. The app keeps
-- connecting as ADMIN and sets ORACLE_SCHEMA=FAMILY_BUDGET, which makes every
-- connection run `ALTER SESSION SET CURRENT_SCHEMA = FAMILY_BUDGET`. Alembic and
-- the ORM then create/read tables in this schema.

-- 1) Schema-only owner + storage quota.
CREATE USER family_budget NO AUTHENTICATION;
ALTER USER family_budget QUOTA UNLIMITED ON DATA;

-- (ADMIN already has privilege to SET CURRENT_SCHEMA to any schema, so no extra
--  grant is needed for the current-schema approach.)

-- 2) Then set the secret and redeploy:
--      fly secrets set ORACLE_SCHEMA=FAMILY_BUDGET -a famo
--    The release step (`alembic upgrade head`) creates every table in
--    FAMILY_BUDGET (a fresh schema → fresh tables).

-- ──────────────────────────────────────────────────────────────────────────
-- OPTIONAL: move EXISTING data from the ADMIN schema into the new one instead
-- of starting fresh. Do this BEFORE pointing the app at the new schema. The
-- cleanest preserving method is Data Pump with a schema remap (run in Database
-- Actions → Data Pump, or via DBMS_DATAPUMP) — it carries tables, identity
-- columns, constraints and indexes automatically:
--
--   expdp ... SCHEMAS=ADMIN
--   impdp ... REMAP_SCHEMA=ADMIN:FAMILY_BUDGET
--
-- Or, simplest for a small dataset: create the empty tables first (set
-- ORACLE_SCHEMA + `alembic upgrade head`), then copy row data in FK order:
--   INSERT INTO family_budget.families       SELECT * FROM admin.families;
--   INSERT INTO family_budget.users          SELECT * FROM admin.users;
--   INSERT INTO family_budget.categories     SELECT * FROM admin.categories;
--   INSERT INTO family_budget.wallets        SELECT * FROM admin.wallets;
--   INSERT INTO family_budget.transactions   SELECT * FROM admin.transactions;
--   INSERT INTO family_budget.budgets        SELECT * FROM admin.budgets;
--   INSERT INTO family_budget.invitations    SELECT * FROM admin.invitations;
--   INSERT INTO family_budget.exchange_rates SELECT * FROM admin.exchange_rates;
--   COMMIT;
-- (Identity columns are GENERATED BY DEFAULT, so explicit ids insert fine; after
--  copying, the next inserted id continues past the max — verify on Oracle.)
--
-- Once the app runs cleanly on the new schema, the old ADMIN-schema tables can
-- be dropped.
